/* eslint-disable */
/**
 * This file was generated by 'vite-plugin-kit-routes'
 *
 *      >> DO NOT EDIT THIS FILE MANUALLY <<
 */

/**
 * PAGES
 */
const PAGES = {
  "/[locale=locale]": (params: { locale: (ExtractParamType<typeof import('../params/locale.ts').match>) }) => {
    return `/${params['locale']}`
  },
  "/[locale=locale]/admin/members": (params: { locale: (ExtractParamType<typeof import('../params/locale.ts').match>) }) => {
    return `/${params['locale']}/admin/members`
  },
  "/[locale=locale]/admin/members/import": (params: { locale: (ExtractParamType<typeof import('../params/locale.ts').match>) }) => {
    return `/${params['locale']}/admin/members/import`
  },
  "/[locale=locale]/admin/membership-types": (params: { locale: (ExtractParamType<typeof import('../params/locale.ts').match>) }) => {
    return `/${params['locale']}/admin/membership-types`
  },
  "/[locale=locale]/admin/memberships": (params: { locale: (ExtractParamType<typeof import('../params/locale.ts').match>) }) => {
    return `/${params['locale']}/admin/memberships`
  },
  "/[locale=locale]/admin/users": (params: { locale: (ExtractParamType<typeof import('../params/locale.ts').match>) }) => {
    return `/${params['locale']}/admin/users`
  },
  "/[locale=locale]/membership": (params: { locale: (ExtractParamType<typeof import('../params/locale.ts').match>) }) => {
    return `/${params['locale']}/membership`
  },
  "/[locale=locale]/new": (params: { locale: (ExtractParamType<typeof import('../params/locale.ts').match>) }) => {
    return `/${params['locale']}/new`
  },
  "/[locale=locale]/settings/emails": (params: { locale: (ExtractParamType<typeof import('../params/locale.ts').match>) }) => {
    return `/${params['locale']}/settings/emails`
  },
  "/[locale=locale]/settings/emails/add": (params: { locale: (ExtractParamType<typeof import('../params/locale.ts').match>) }) => {
    return `/${params['locale']}/settings/emails/add`
  },
  "/[locale=locale]/settings/emails/verify": (params: { locale: (ExtractParamType<typeof import('../params/locale.ts').match>) }) => {
    return `/${params['locale']}/settings/emails/verify`
  },
  "/[locale=locale]/settings/passkeys": (params: { locale: (ExtractParamType<typeof import('../params/locale.ts').match>) }) => {
    return `/${params['locale']}/settings/passkeys`
  },
  "/[locale=locale]/settings/profile": (params: { locale: (ExtractParamType<typeof import('../params/locale.ts').match>) }) => {
    return `/${params['locale']}/settings/profile`
  },
  "/[locale=locale]/privacy-policy": (params: { locale: (ExtractParamType<typeof import('../params/locale.ts').match>) }) => {
    return `/${params['locale']}/privacy-policy`
  },
  "/[locale=locale]/sign-in": (params: { locale: (ExtractParamType<typeof import('../params/locale.ts').match>) }) => {
    return `/${params['locale']}/sign-in`
  },
  "/[locale=locale]/sign-in/email": (params: { locale: (ExtractParamType<typeof import('../params/locale.ts').match>) }) => {
    return `/${params['locale']}/sign-in/email`
  },
  "/[locale=locale]/sign-in/method": (params: { locale: (ExtractParamType<typeof import('../params/locale.ts').match>) }) => {
    return `/${params['locale']}/sign-in/method`
  }
}

/**
 * SERVERS
 */
const SERVERS = {
  "GET /api/health": `/api/health`,
  "POST /api/webhook/stripe": `/api/webhook/stripe`
}

/**
 * ACTIONS
 */
const ACTIONS = {
  
}

/**
 * LINKS
 */
const LINKS = {
  
}

type ParamValue = string | number | boolean | null | undefined

/**
 * Append search params to a string
 */
export const appendSp = (
  sp?: Record<string, ParamValue | ParamValue[]>,
  prefix: '?' | '&' = '?',
) => {
  if (sp === undefined) return ''

  const params = new URLSearchParams()
  const append = (n: string, v: ParamValue) => {
    if (v !== undefined) {
      params.append(n, String(v))
    }
  }

  let anchor = ''
  for (const [name, val] of Object.entries(sp)) {
    if (name === '__KIT_ROUTES_ANCHOR__' && val !== undefined) {
      anchor = `#${val}`
      continue
    }
    if (Array.isArray(val)) {
      for (const v of val) {
        append(name, v)
      }
    } else {
      append(name, val)
    }
  }

  const formatted = params.toString()
  if (formatted || anchor) {
    return `${prefix}${formatted}${anchor}`.replace('?#', '#')
  }
  return ''
}

/**
 * get the current search params
 * 
 * Could be use like this:
 * ```
 * route("/cities", { page: 2 }, { ...currentSP() })
 * ```
 */ 
export const currentSp = () => {
  const params = new URLSearchParams(window.location.search)
  const record: Record<string, string> = {}
  for (const [key, value] of params.entries()) {
    record[key] = value
  }
  return record
}

/* type helpers for route function */
type NonFunctionKeys<T> = { [K in keyof T]: T[K] extends Function ? never : K }[keyof T]
type FunctionKeys<T> = { [K in keyof T]: T[K] extends Function ? K : never }[keyof T]
type FunctionParams<T> = T extends (...args: infer P) => any ? P : never

const AllObjs = { ...PAGES, ...ACTIONS, ...SERVERS, ...LINKS }
type AllTypes = typeof AllObjs

export type Routes = keyof AllTypes extends `${string}/${infer Route}` ? `/${Route}` : keyof AllTypes
export const routes = [
	...new Set(Object.keys(AllObjs).map((route) => /^\/.*|[^ ]?\/.*$/.exec(route)?.[0] ?? route)),
] as Routes[]

/**
 * To be used like this: 
 * ```ts
 * import { route } from './ROUTES'
 * 
 * route('site_id', { id: 1 })
 * ```
 */
export function route<T extends FunctionKeys<AllTypes>>(key: T, ...params: FunctionParams<AllTypes[T]>): string
export function route<T extends NonFunctionKeys<AllTypes>>(key: T): string
export function route<T extends keyof AllTypes>(key: T, ...params: any[]): string {
  if (AllObjs[key] as any instanceof Function) {
    const element = (AllObjs as any)[key] as (...args: any[]) => string
    return element(...params)
  } else {
    return AllObjs[key] as string
  }
}

/* type helpers param & predicate */
type ExtractFnPredicate<T> = T extends (param: any) => param is infer U ? U : never;
type ExtractParamType<T extends (param: any) => any> = ExtractFnPredicate<T> extends never ? Parameters<T>[0] : ExtractFnPredicate<T>

/**
* Add this type as a generic of the vite plugin `kitRoutes<KIT_ROUTES>`.
*
* Full example:
* ```ts
* import type { KIT_ROUTES } from '$lib/ROUTES'
* import { kitRoutes } from 'vite-plugin-kit-routes'
*
* kitRoutes<KIT_ROUTES>({
*  PAGES: {
*    // here, key of object will be typed!
*  }
* })
* ```
*/
export type KIT_ROUTES = {
  PAGES: { '/[locale=locale]': 'locale', '/[locale=locale]/admin/members': 'locale', '/[locale=locale]/admin/members/import': 'locale', '/[locale=locale]/admin/membership-types': 'locale', '/[locale=locale]/admin/memberships': 'locale', '/[locale=locale]/admin/users': 'locale', '/[locale=locale]/membership': 'locale', '/[locale=locale]/new': 'locale', '/[locale=locale]/settings/emails': 'locale', '/[locale=locale]/settings/emails/add': 'locale', '/[locale=locale]/settings/emails/verify': 'locale', '/[locale=locale]/settings/passkeys': 'locale', '/[locale=locale]/settings/profile': 'locale', '/[locale=locale]/privacy-policy': 'locale', '/[locale=locale]/sign-in': 'locale', '/[locale=locale]/sign-in/email': 'locale', '/[locale=locale]/sign-in/method': 'locale' }
  SERVERS: { 'GET /api/health': never, 'POST /api/webhook/stripe': never }
  ACTIONS: Record<string, never>
  LINKS: Record<string, never>
  Params: { 'locale': never }
}
