name: i18n

on:
  push:

permissions:
  contents: read

jobs:
  checks:
    name: validate and lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@d648c2dd069001a242c621c8306af467f150e99d

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Validate
        run: pnpm i18n:validate

      - name: Lint
        run: pnpm i18n:lint
