name: "nix flake check"
on:
  pull_request:
  push:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@526118121621777ccd86f79b04685a9319637641
        with:
          nix_path: nixpkgs=channel:nixos-24.11
      - uses: DeterminateSystems/magic-nix-cache-action@b0a6a315e2cd8d9608f6164b8c955b1af05d351e
      - name: nix flake check
        run: nix flake check --no-pure-eval --all-systems --accept-flake-config -L
